export const artists = [
  {
    name: 'Kendrick Lamar',
    imageUrl: 'https://i.pravatar.cc/300?img=40',
    description: 'American rapper, songwriter, and record producer',
    isFeatured: true,
  },
  {
    name: 'Future',
    imageUrl: 'https://i.pravatar.cc/300?img=2',
    description: 'American rapper, singer, songwriter, and record producer',
    isFeatured: true,
  },
  {
    name: 'Shaboozey',
    imageUrl: 'https://i.pravatar.cc/300?img=67',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Post Malone',
    imageUrl: 'https://i.pravatar.cc/300?img=20',
    description: 'American rapper, singer, songwriter, and record producer',
    isFeatured: true,
  },
  {
    name: 'SZA',
    imageUrl: 'https://i.pravatar.cc/300?img=2',
    description: 'American singer and songwriter',
    isFeatured: true,
  },
  {
    name: 'Morgan Wallen',
    imageUrl: 'https://i.pravatar.cc/300?img=63',
    description: 'American country music singer and songwriter',
    isFeatured: true,
  },
  {
    name: 'Zach Bryan',
    imageUrl: 'https://i.pravatar.cc/300?img=7',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Benson Boone',
    imageUrl: 'https://i.pravatar.cc/300?img=35',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Lil Baby',
    imageUrl: 'https://i.pravatar.cc/300?img=13',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Teddy Swims',
    imageUrl: 'https://i.pravatar.cc/300?img=49',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Sabrina Carpenter',
    imageUrl: 'https://i.pravatar.cc/300?img=51',
    description: 'American singer and actress',
    isFeatured: false,
  },
  {
    name: 'Jack Harlow',
    imageUrl: 'https://i.pravatar.cc/300?img=65',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Noah Kahan',
    imageUrl: 'https://i.pravatar.cc/300?img=52',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Tommy Richman',
    imageUrl: 'https://i.pravatar.cc/300?img=61',
    description: 'American singer',
    isFeatured: false,
  },
  {
    name: 'Billie Eilish',
    imageUrl: 'https://i.pravatar.cc/300?img=67',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Drake',
    imageUrl: 'https://i.pravatar.cc/300?img=24',
    description: 'Canadian rapper, singer, songwriter, and actor',
    isFeatured: true,
  },
  {
    name: '\u00a5$',
    imageUrl: 'https://i.pravatar.cc/300?img=17',
    description: 'Musical duo',
    isFeatured: false,
  },
  {
    name: 'Luke Combs',
    imageUrl: 'https://i.pravatar.cc/300?img=16',
    description: 'American country music singer and songwriter',
    isFeatured: false,
  },
  {
    name: 'Hozier',
    imageUrl: 'https://i.pravatar.cc/300?img=8',
    description: 'Irish singer-songwriter and musician',
    isFeatured: false,
  },
  {
    name: 'Taylor Swift',
    imageUrl: 'https://i.pravatar.cc/300?img=34',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'GloRilla',
    imageUrl: 'https://i.pravatar.cc/300?img=24',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Doja Cat',
    imageUrl: 'https://i.pravatar.cc/300?img=69',
    description: 'American rapper, singer, songwriter, and record producer',
    isFeatured: false,
  },
  {
    name: '21 Savage',
    imageUrl: 'https://i.pravatar.cc/300?img=59',
    description: 'British-American rapper',
    isFeatured: false,
  },
  {
    name: 'Bryson Tiller',
    imageUrl: 'https://i.pravatar.cc/300?img=41',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'BossMan Dlow',
    imageUrl: 'https://i.pravatar.cc/300?img=24',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Travis Scott',
    imageUrl: 'https://i.pravatar.cc/300?img=17',
    description: 'American rapper, singer, songwriter, and record producer',
    isFeatured: false,
  },
  {
    name: 'Chris Stapleton',
    imageUrl: 'https://i.pravatar.cc/300?img=4',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'J. Cole',
    imageUrl: 'https://i.pravatar.cc/300?img=54',
    description: 'American rapper, singer, songwriter, and record producer',
    isFeatured: false,
  },
  {
    name: 'Tate McRae',
    imageUrl: 'https://i.pravatar.cc/300?img=70',
    description: 'Canadian singer-songwriter and dancer',
    isFeatured: false,
  },
  {
    name: 'FloyyMenor',
    imageUrl: 'https://i.pravatar.cc/300?img=29',
    description: 'Brazilian singer',
    isFeatured: false,
  },
  {
    name: 'Gunna',
    imageUrl: 'https://i.pravatar.cc/300?img=26',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'YoungBoy Never Broke Again',
    imageUrl: 'https://i.pravatar.cc/300?img=60',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Chappell Roan',
    imageUrl: 'https://i.pravatar.cc/300?img=47',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Chris Brown',
    imageUrl: 'https://i.pravatar.cc/300?img=2',
    description: 'American singer, songwriter, dancer, and actor',
    isFeatured: false,
  },
  {
    name: 'Rod Wave',
    imageUrl: 'https://i.pravatar.cc/300?img=30',
    description: 'American rapper and singer',
    isFeatured: false,
  },
  {
    name: 'Kodak Black',
    imageUrl: 'https://i.pravatar.cc/300?img=14',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Muni Long',
    imageUrl: 'https://i.pravatar.cc/300?img=35',
    description: 'American singer and songwriter',
    isFeatured: false,
  },
  {
    name: 'Jhen\u00e9 Aiko',
    imageUrl: 'https://i.pravatar.cc/300?img=26',
    description: 'American singer and songwriter',
    isFeatured: false,
  },
  {
    name: 'BigXthaPlug',
    imageUrl: 'https://i.pravatar.cc/300?img=8',
    description: 'American rapper',
    isFeatured: false,
  },
  {
    name: 'Summer Walker',
    imageUrl: 'https://i.pravatar.cc/300?img=3',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Xavi',
    imageUrl: 'https://i.pravatar.cc/300?img=42',
    description: 'Mexican-American singer',
    isFeatured: false,
  },
  {
    name: 'Frank Ocean',
    imageUrl: 'https://i.pravatar.cc/300?img=46',
    description: 'American singer-songwriter',
    isFeatured: false,
  },
  {
    name: 'Lil Durk',
    imageUrl: 'https://i.pravatar.cc/300?img=8',
    description: 'American rapper and singer',
    isFeatured: false,
  },
  {
    name: 'Fuerza Regida',
    imageUrl: 'https://i.pravatar.cc/300?img=28',
    description: 'Mexican band',
    isFeatured: false,
  },
  {
    name: 'Peso Pluma',
    imageUrl: 'https://i.pravatar.cc/300?img=23',
    description: 'Mexican singer',
    isFeatured: false,
  },
];