export const songs = [
  {
    albumTitle: 'Not Like Us - Single',
    songs: [
      {
        title: 'Not Like Us',
        duration: 634,
        url: '/Not Like Us.mp3',
        isFeatured: true,
        releaseDate: '2024-05-04',
        imageUrl: 'https://picsum.photos/seed/497/300/300',
      },
    ],
  },
  {
    albumTitle: "WE DON'T TRUST YOU",
    songs: [
      {
        title: 'Like That',
        duration: 617,
        url: '/Like That.mp3',
        isFeatured: true,
        releaseDate: '2024-03-22',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
      {
        title: 'Type Shit',
        duration: 320,
        url: '/Type Shit.mp3',
        isFeatured: false,
        releaseDate: '2024-03-22',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
      {
        title: 'WAIT FOR U (feat. Drake & Tems)',
        duration: 249,
        url: '/WAIT FOR U (feat. Drake & Tems).mp3',
        isFeatured: false,
        releaseDate: '2022-04-29',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
      {
        title: 'Stick Talk',
        duration: 206,
        url: '/Stick Talk.mp3',
        isFeatured: false,
        releaseDate: '2024-03-22',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
      {
        title: 'March Madness',
        duration: 342,
        url: '/March Madness.mp3',
        isFeatured: false,
        releaseDate: '2015-07-17',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
      {
        title: 'Mask Off',
        duration: 209,
        url: '/Mask Off.mp3',
        isFeatured: false,
        releaseDate: '2017-02-24',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
      {
        title: 'Low Life (feat. The Weeknd)',
        duration: 366,
        url: '/Low Life (feat. The Weeknd).mp3',
        isFeatured: false,
        releaseDate: '2016-02-05',
        imageUrl: 'https://picsum.photos/seed/851/300/300',
      },
    ],
  },
  {
    albumTitle: 'A Bar Song (Tipsy) - Single',
    songs: [
      {
        title: 'A Bar Song (Tipsy)',
        duration: 389,
        url: '/A Bar Song (Tipsy).mp3',
        isFeatured: false,
        releaseDate: '2024-04-05',
        imageUrl: 'https://picsum.photos/seed/869/300/300',
      },
    ],
  },
  {
    albumTitle: 'I Had Some Help - Single',
    songs: [
      {
        title: 'I Had Some Help',
        duration: 269,
        url: '/I Had Some Help.mp3',
        isFeatured: false,
        releaseDate: '2024-05-10',
        imageUrl: 'https://picsum.photos/seed/679/300/300',
      },
    ],
  },
  {
    albumTitle: 'SOS',
    songs: [
      {
        title: 'Snooze',
        duration: 245,
        url: '/Snooze.mp3',
        isFeatured: true,
        releaseDate: '2022-12-09',
        imageUrl: 'https://picsum.photos/seed/415/300/300',
      },
      {
        title: 'Saturn',
        duration: 194,
        url: '/Saturn.mp3',
        isFeatured: false,
        releaseDate: '2023-02-09',
        imageUrl: 'https://picsum.photos/seed/415/300/300',
      },
      {
        title: 'Good Days',
        duration: 277,
        url: '/Good Days.mp3',
        isFeatured: false,
        releaseDate: '2020-12-25',
        imageUrl: 'https://picsum.photos/seed/415/300/300',
      },
      {
        title: 'Kill Bill',
        duration: 153,
        url: '/Kill Bill.mp3',
        isFeatured: false,
        releaseDate: '2022-12-09',
        imageUrl: 'https://picsum.photos/seed/415/300/300',
      },
      {
        title: 'Nobody Gets Me',
        duration: 231,
        url: '/Nobody Gets Me.mp3',
        isFeatured: false,
        releaseDate: '2022-12-09',
        imageUrl: 'https://picsum.photos/seed/415/300/300',
      },
    ],
  },
  {
    albumTitle: 'One Thing At a Time',
    songs: [
      {
        title: 'Last Night',
        duration: 196,
        url: '/Last Night.mp3',
        isFeatured: true,
        releaseDate: '2023-03-03',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'Thinkin\u2019 Bout Me',
        duration: 208,
        url: '/Thinkin\u2019 Bout Me.mp3',
        isFeatured: false,
        releaseDate: '2023-03-03',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'Cowgirls',
        duration: 214,
        url: '/Cowgirls.mp3',
        isFeatured: false,
        releaseDate: '2023-03-03',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: "Chasin' You",
        duration: 237,
        url: "/Chasin' You.mp3",
        isFeatured: false,
        releaseDate: '2019-07-26',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'You Proof',
        duration: 183,
        url: '/You Proof.mp3',
        isFeatured: false,
        releaseDate: '2022-05-13',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'Wasted On You',
        duration: 213,
        url: '/Wasted On You.mp3',
        isFeatured: false,
        releaseDate: '2021-01-08',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'Spin You Around (1_24)',
        duration: 248,
        url: '/Spin You Around (1_24).mp3',
        isFeatured: false,
        releaseDate: '2023-03-03',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'More Than My Hometown',
        duration: 257,
        url: '/More Than My Hometown.mp3',
        isFeatured: false,
        releaseDate: '2020-06-12',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
      {
        title: 'Lies Lies Lies',
        duration: 231,
        url: '/Lies Lies Lies.mp3',
        isFeatured: false,
        releaseDate: '2021-04-23',
        imageUrl: 'https://picsum.photos/seed/335/300/300',
      },
    ],
  },
  {
    albumTitle: 'Zach Bryan',
    songs: [
      {
        title: 'I Remember Everything (feat. Kacey Musgraves)',
        duration: 263,
        url: '/I Remember Everything (feat. Kacey Musgraves).mp3',
        isFeatured: true,
        releaseDate: '2023-08-25',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
      {
        title: 'Pink Skies',
        duration: 220,
        url: '/Pink Skies.mp3',
        isFeatured: false,
        releaseDate: '2023-08-25',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
      {
        title: 'Oklahoma Smokeshow',
        duration: 202,
        url: '/Oklahoma Smokeshow.mp3',
        isFeatured: false,
        releaseDate: '2023-08-25',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
      {
        title: 'Something in the Orange',
        duration: 208,
        url: '/Something in the Orange.mp3',
        isFeatured: false,
        releaseDate: '2022-04-22',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
      {
        title: 'Revival',
        duration: 226,
        url: '/Revival.mp3',
        isFeatured: false,
        releaseDate: '2023-08-25',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
      {
        title: 'Tourniquet',
        duration: 214,
        url: '/Tourniquet.mp3',
        isFeatured: false,
        releaseDate: '2023-08-25',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
      {
        title: 'Burn, Burn, Burn',
        duration: 246,
        url: '/Burn, Burn, Burn.mp3',
        isFeatured: false,
        releaseDate: '2023-08-25',
        imageUrl: 'https://picsum.photos/seed/66/300/300',
      },
    ],
  },
  {
    albumTitle: 'Beautiful Things - Single',
    songs: [
      {
        title: 'Beautiful Things',
        duration: 204,
        url: '/Beautiful Things.mp3',
        isFeatured: false,
        releaseDate: '2024-01-18',
        imageUrl: 'https://picsum.photos/seed/545/300/300',
      },
    ],
  },
  {
    albumTitle: 'Street Gossip',
    songs: [
      {
        title: 'Freestyle',
        duration: 189,
        url: '/Freestyle.mp3',
        isFeatured: false,
        releaseDate: '2018-11-30',
        imageUrl: 'https://picsum.photos/seed/688/300/300',
      },
      {
        title: 'Sum 2 Prove',
        duration: 247,
        url: '/Sum 2 Prove.mp3',
        isFeatured: false,
        releaseDate: '2020-02-28',
        imageUrl: 'https://picsum.photos/seed/688/300/300',
      },
      {
        title: 'Low Down',
        duration: 176,
        url: '/Low Down.mp3',
        isFeatured: false,
        releaseDate: '2018-11-30',
        imageUrl: 'https://picsum.photos/seed/688/300/300',
      },
      {
        title: 'Woah',
        duration: 191,
        url: '/Woah.mp3',
        isFeatured: false,
        releaseDate: '2019-11-29',
        imageUrl: 'https://picsum.photos/seed/688/300/300',
      },
      {
        title: 'In A Minute',
        duration: 238,
        url: '/In A Minute.mp3',
        isFeatured: false,
        releaseDate: '2020-02-28',
        imageUrl: 'https://picsum.photos/seed/688/300/300',
      },
    ],
  },
  {
    albumTitle: "I've Tried Everything Dear But I Think I'm Gonna Kill Myself",
    songs: [
      {
        title: 'Lose Control',
        duration: 222,
        url: '/Lose Control.mp3',
        isFeatured: false,
        releaseDate: '2023-09-29',
        imageUrl: 'https://picsum.photos/seed/364/300/300',
      },
    ],
  },
  {
    albumTitle: 'Espresso - Single',
    songs: [
      {
        title: 'Espresso',
        duration: 189,
        url: '/Espresso.mp3',
        isFeatured: false,
        releaseDate: '2024-05-22',
        imageUrl: 'https://picsum.photos/seed/566/300/300',
      },
    ],
  },
  {
    albumTitle: 'Jack Harlow Come Home the Kids Miss You',
    songs: [
      {
        title: 'Lovin On Me',
        duration: 190,
        url: '/Lovin On Me.mp3',
        isFeatured: false,
        releaseDate: '2023-11-10',
        imageUrl: 'https://picsum.photos/seed/95/300/300',
      },
    ],
  },
  {
    albumTitle: 'Stick Season',
    songs: [
      {
        title: 'Stick Season',
        duration: 212,
        url: '/Stick Season.mp3',
        isFeatured: false,
        releaseDate: '2022-10-14',
        imageUrl: 'https://picsum.photos/seed/290/300/300',
      },
    ],
  },
  {
    albumTitle: 'MILLION DOLLAR BABY - Single',
    songs: [
      {
        title: 'MILLION DOLLAR BABY',
        duration: 179,
        url: '/MILLION DOLLAR BABY.mp3',
        isFeatured: false,
        releaseDate: '2024-04-26',
        imageUrl: 'https://picsum.photos/seed/27/300/300',
      },
    ],
  },
  {
    albumTitle: 'HIT ME HARD AND SOFT',
    songs: [
      {
        title: 'BIRDS OF A FEATHER',
        duration: 247,
        url: '/BIRDS OF A FEATHER.mp3',
        isFeatured: false,
        releaseDate: '2024-05-17',
        imageUrl: 'https://picsum.photos/seed/149/300/300',
      },
      {
        title: 'WILDFLOWER',
        duration: 302,
        url: '/WILDFLOWER.mp3',
        isFeatured: false,
        releaseDate: '2024-05-17',
        imageUrl: 'https://picsum.photos/seed/149/300/300',
      },
    ],
  },
  {
    albumTitle: 'So Far Gone',
    songs: [
      {
        title: 'Best I Ever Had',
        duration: 257,
        url: '/Best I Ever Had.mp3',
        isFeatured: false,
        releaseDate: '2009-09-15',
        imageUrl: 'https://picsum.photos/seed/923/300/300',
      },
    ],
  },
  {
    albumTitle: 'Please Please Please - Single',
    songs: [
      {
        title: 'Please Please Please',
        duration: 200,
        url: '/Please Please Please.mp3',
        isFeatured: false,
        releaseDate: '2024-06-06',
        imageUrl: 'https://picsum.photos/seed/228/300/300',
      },
    ],
  },
  {
    albumTitle: 'For All The Dogs',
    songs: [
      {
        title: 'Rich Baby Daddy',
        duration: 395,
        url: '/Rich Baby Daddy.mp3',
        isFeatured: false,
        releaseDate: '2023-10-06',
        imageUrl: 'https://picsum.photos/seed/819/300/300',
      },
    ],
  },
  {
    albumTitle: 'Get It Sexyy - Single',
    songs: [
      {
        title: 'Get It Sexyy',
        duration: 178,
        url: '/Get It Sexyy.mp3',
        isFeatured: false,
        releaseDate: '2023-06-02',
        imageUrl: 'https://picsum.photos/seed/513/300/300',
      },
    ],
  },
  {
    albumTitle: 'I NEVER LIKED YOU',
    songs: [
      {
        title: 'WAIT FOR U (feat. Drake & Tems)',
        duration: 249,
        url: '/WAIT FOR U (feat. Drake & Tems).mp3',
        isFeatured: false,
        releaseDate: '2022-04-29',
        imageUrl: 'https://picsum.photos/seed/818/300/300',
      },
    ],
  },
  {
    albumTitle: 'Vultures 1',
    songs: [
      {
        title: 'CARNIVAL (feat. Rich The Kid, Playboi Carti)',
        duration: 304,
        url: '/CARNIVAL (feat. Rich The Kid, Playboi Carti).mp3',
        isFeatured: false,
        releaseDate: '2024-02-10',
        imageUrl: 'https://picsum.photos/seed/900/300/300',
      },
    ],
  },
  {
    albumTitle: 'Too Sweet - Single',
    songs: [
      {
        title: 'Too Sweet',
        duration: 312,
        url: '/Too Sweet.mp3',
        isFeatured: false,
        releaseDate: '2024-03-22',
        imageUrl: 'https://picsum.photos/seed/643/300/300',
      },
    ],
  },
  {
    albumTitle: 'Fast Car - Single',
    songs: [
      {
        title: 'Fast Car',
        duration: 290,
        url: '/Fast Car.mp3',
        isFeatured: false,
        releaseDate: '2023-04-07',
        imageUrl: 'https://picsum.photos/seed/960/300/300',
      },
    ],
  },
  {
    albumTitle: 'Yeah Glo! - Single',
    songs: [
      {
        title: 'Yeah Glo!',
        duration: 171,
        url: '/Yeah Glo!.mp3',
        isFeatured: false,
        releaseDate: '2024-05-17',
        imageUrl: 'https://picsum.photos/seed/969/300/300',
      },
    ],
  },
  {
    albumTitle: 'Agora Hills - Single',
    songs: [
      {
        title: 'Agora Hills',
        duration: 310,
        url: '/Agora Hills.mp3',
        isFeatured: false,
        releaseDate: '2023-08-04',
        imageUrl: 'https://picsum.photos/seed/975/300/300',
      },
    ],
  },
  {
    albumTitle: 'American Dream',
    songs: [
      {
        title: 'redrum',
        duration: 382,
        url: '/redrum.mp3',
        isFeatured: false,
        releaseDate: '2024-01-12',
        imageUrl: 'https://picsum.photos/seed/657/300/300',
      },
    ],
  },
  {
    albumTitle: 'TRAPSOUL',
    songs: [
      {
        title: 'Whatever She Wants',
        duration: 198,
        url: '/Whatever She Wants.mp3',
        isFeatured: false,
        releaseDate: '2024-05-17',
        imageUrl: 'https://picsum.photos/seed/33/300/300',
      },
      {
        title: "Don't",
        duration: 206,
        url: "/Don't.mp3",
        isFeatured: false,
        releaseDate: '2015-10-02',
        imageUrl: 'https://picsum.photos/seed/33/300/300',
      },
      {
        title: 'Exchange',
        duration: 256,
        url: '/Exchange.mp3',
        isFeatured: false,
        releaseDate: '2015-10-02',
        imageUrl: 'https://picsum.photos/seed/33/300/300',
      },
    ],
  },
  {
    albumTitle: 'UTOPIA',
    songs: [
      {
        title: 'FE!N (feat. Playboi Carti)',
        duration: 208,
        url: '/FE!N (feat. Playboi Carti).mp3',
        isFeatured: false,
        releaseDate: '2023-07-28',
        imageUrl: 'https://picsum.photos/seed/549/300/300',
      },
      {
        title: 'HIGHEST IN THE ROOM',
        duration: 175,
        url: '/HIGHEST IN THE ROOM.mp3',
        isFeatured: false,
        releaseDate: '2019-10-04',
        imageUrl: 'https://picsum.photos/seed/549/300/300',
      },
    ],
  },
  {
    albumTitle: 'Traveller',
    songs: [
      {
        title: 'Tennessee Whiskey',
        duration: 285,
        url: '/Tennessee Whiskey.mp3',
        isFeatured: false,
        releaseDate: '2015-05-05',
        imageUrl: 'https://picsum.photos/seed/129/300/300',
      },
    ],
  },
  {
    albumTitle: 'Born Sinner',
    songs: [
      {
        title: 'Power Trip',
        duration: 274,
        url: '/Power Trip.mp3',
        isFeatured: false,
        releaseDate: '2013-06-18',
        imageUrl: 'https://picsum.photos/seed/855/300/300',
      },
    ],
  },
  {
    albumTitle: 'Scorpion',
    songs: [
      {
        title: 'Nonstop',
        duration: 239,
        url: '/Nonstop.mp3',
        isFeatured: false,
        releaseDate: '2018-06-29',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: 'You Broke My Heart',
        duration: 265,
        url: '/You Broke My Heart.mp3',
        isFeatured: false,
        releaseDate: '2023-10-06',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: 'Wants and Needs',
        duration: 194,
        url: '/Wants and Needs.mp3',
        isFeatured: false,
        releaseDate: '2021-03-05',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: 'Virginia Beach',
        duration: 295,
        url: '/Virginia Beach.mp3',
        isFeatured: false,
        releaseDate: '2023-10-06',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: "God's Plan",
        duration: 198,
        url: "/God's Plan.mp3",
        isFeatured: false,
        releaseDate: '2018-01-19',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: 'Passionfruit',
        duration: 288,
        url: '/Passionfruit.mp3',
        isFeatured: false,
        releaseDate: '2017-03-18',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: 'No Guidance (feat. Drake)',
        duration: 261,
        url: '/No Guidance (feat. Drake).mp3',
        isFeatured: false,
        releaseDate: '2019-06-28',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
      {
        title: 'IDGAF',
        duration: 240,
        url: '/IDGAF.mp3',
        isFeatured: false,
        releaseDate: '2023-10-06',
        imageUrl: 'https://picsum.photos/seed/599/300/300',
      },
    ],
  },
  {
    albumTitle: 'Beautiful Crazy - Single',
    songs: [
      {
        title: 'Beautiful Crazy',
        duration: 212,
        url: '/Beautiful Crazy.mp3',
        isFeatured: false,
        releaseDate: '2018-12-14',
        imageUrl: 'https://picsum.photos/seed/884/300/300',
      },
    ],
  },
  {
    albumTitle: 'The Tortured Poets Department',
    songs: [
      {
        title: 'Fortnight',
        duration: 228,
        url: '/Fortnight.mp3',
        isFeatured: false,
        releaseDate: '2024-04-19',
        imageUrl: 'https://picsum.photos/seed/813/300/300',
      },
    ],
  },
  {
    albumTitle: "Gettin' Old",
    songs: [
      {
        title: 'Where the Wild Things Are',
        duration: 270,
        url: '/Where the Wild Things Are.mp3',
        isFeatured: false,
        releaseDate: '2023-03-24',
        imageUrl: 'https://picsum.photos/seed/267/300/300',
      },
    ],
  },
  {
    albumTitle: 'greedy - Single',
    songs: [
      {
        title: 'greedy',
        duration: 175,
        url: '/greedy.mp3',
        isFeatured: false,
        releaseDate: '2023-09-15',
        imageUrl: 'https://picsum.photos/seed/154/300/300',
      },
    ],
  },
  {
    albumTitle: 'Certified Lover Boy',
    songs: [
      {
        title: 'Knife Talk',
        duration: 212,
        url: '/Knife Talk.mp3',
        isFeatured: false,
        releaseDate: '2021-09-03',
        imageUrl: 'https://picsum.photos/seed/869/300/300',
      },
      {
        title: 'First Person Shooter',
        duration: 211,
        url: '/First Person Shooter.mp3',
        isFeatured: false,
        releaseDate: '2023-10-06',
        imageUrl: 'https://picsum.photos/seed/869/300/300',
      },
    ],
  },
  {
    albumTitle: 'Gata Only - Single',
    songs: [
      {
        title: 'Gata Only',
        duration: 206,
        url: '/Gata Only.mp3',
        isFeatured: false,
        releaseDate: '2024-05-03',
        imageUrl: 'https://picsum.photos/seed/271/300/300',
      },
    ],
  },
  {
    albumTitle: 'My Turn',
    songs: [
      {
        title: 'Woah',
        duration: 191,
        url: '/Woah.mp3',
        isFeatured: false,
        releaseDate: '2019-11-29',
        imageUrl: 'https://picsum.photos/seed/946/300/300',
      },
    ],
  },
  {
    albumTitle: 'a Gift & a Curse',
    songs: [
      {
        title: 'fukumean',
        duration: 161,
        url: '/fukumean.mp3',
        isFeatured: false,
        releaseDate: '2023-06-16',
        imageUrl: 'https://picsum.photos/seed/726/300/300',
      },
    ],
  },
  {
    albumTitle: 'Birds in the Trap Sing McKnight',
    songs: [
      {
        title: 'HIGHEST IN THE ROOM',
        duration: 175,
        url: '/HIGHEST IN THE ROOM.mp3',
        isFeatured: false,
        releaseDate: '2019-10-04',
        imageUrl: 'https://picsum.photos/seed/852/300/300',
      },
    ],
  },
  {
    albumTitle: "Don't Try This At Home",
    songs: [
      {
        title: 'Kacey Talk',
        duration: 197,
        url: '/Kacey Talk.mp3',
        isFeatured: false,
        releaseDate: '2023-04-21',
        imageUrl: 'https://picsum.photos/seed/802/300/300',
      },
      {
        title: 'Valuable Pain',
        duration: 195,
        url: '/Valuable Pain.mp3',
        isFeatured: false,
        releaseDate: '2023-04-21',
        imageUrl: 'https://picsum.photos/seed/802/300/300',
      },
    ],
  },
  {
    albumTitle: 'Good Luck, Babe! - Single',
    songs: [
      {
        title: 'Good Luck, Babe!',
        duration: 204,
        url: '/Good Luck, Babe!.mp3',
        isFeatured: false,
        releaseDate: '2024-06-28',
        imageUrl: 'https://picsum.photos/seed/260/300/300',
      },
    ],
  },
  {
    albumTitle: 'Issa Album',
    songs: [
      {
        title: 'Bank Account',
        duration: 205,
        url: '/Bank Account.mp3',
        isFeatured: false,
        releaseDate: '2017-06-16',
        imageUrl: 'https://picsum.photos/seed/326/300/300',
      },
    ],
  },
  {
    albumTitle: 'Indigo',
    songs: [
      {
        title: 'Under The Influence',
        duration: 192,
        url: '/Under The Influence.mp3',
        isFeatured: false,
        releaseDate: '2019-06-28',
        imageUrl: 'https://picsum.photos/seed/951/300/300',
      },
    ],
  },
  {
    albumTitle: 'Nostalgia',
    songs: [
      {
        title: 'Great Gatsby',
        duration: 168,
        url: '/Great Gatsby.mp3',
        isFeatured: false,
        releaseDate: '2023-09-01',
        imageUrl: 'https://picsum.photos/seed/434/300/300',
      },
    ],
  },
  {
    albumTitle: 'Wanna Be - Single',
    songs: [
      {
        title: 'Wanna Be',
        duration: 194,
        url: '/Wanna Be.mp3',
        isFeatured: false,
        releaseDate: '2024-05-31',
        imageUrl: 'https://picsum.photos/seed/67/300/300',
      },
    ],
  },
  {
    albumTitle: 'More Life',
    songs: [
      {
        title: 'Passionfruit',
        duration: 288,
        url: '/Passionfruit.mp3',
        isFeatured: false,
        releaseDate: '2017-03-18',
        imageUrl: 'https://picsum.photos/seed/433/300/300',
      },
    ],
  },
  {
    albumTitle: 'Dying to Live',
    songs: [
      {
        title: "No Flockin'",
        duration: 198,
        url: "/No Flockin'.mp3",
        isFeatured: false,
        releaseDate: '2014-06-11',
        imageUrl: 'https://picsum.photos/seed/633/300/300',
      },
    ],
  },
  {
    albumTitle: 'Made For Me - Single',
    songs: [
      {
        title: 'Made For Me',
        duration: 208,
        url: '/Made For Me.mp3',
        isFeatured: false,
        releaseDate: '2023-09-15',
        imageUrl: 'https://picsum.photos/seed/732/300/300',
      },
    ],
  },
  {
    albumTitle: 'Chilombo',
    songs: [
      {
        title: 'Sativa',
        duration: 322,
        url: '/Sativa.mp3',
        isFeatured: false,
        releaseDate: '2017-07-21',
        imageUrl: 'https://picsum.photos/seed/916/300/300',
      },
    ],
  },
  {
    albumTitle: 'Mmhmm - Single',
    songs: [
      {
        title: 'Mmhmm',
        duration: 163,
        url: '/Mmhmm.mp3',
        isFeatured: false,
        releaseDate: '2024-04-26',
        imageUrl: 'https://picsum.photos/seed/341/300/300',
      },
    ],
  },
];